# Dependabot configuration for AIBugBench
# Automated dependency vulnerability scanning and updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    assignees: ["sMiNT0S"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels: ["dependencies"]
    allow:
      - dependency-type: "direct"   # drop indirects to cut noise
    groups:
      requests-group:
        patterns: ["requests*", "urllib3", "certifi"]
      yaml-group:
        patterns: ["pyyaml", "yaml*"]
      dev-tools:                    # no security tools here (avoid overlap)
        patterns: ["ruff", "mypy", "pytest*", "coverage*", "pip-tools"]
      security-tools:
        patterns: ["bandit", "safety", "pip-audit"]
      typing:
        patterns: ["types-*"]
      docs-stack:                   # mkdocs and friends grouped together
        patterns: ["mkdocs*", "pymdown-extensions*", "sphinx*"]

  # GitHub Actions (weekly; you pin SHAs separately)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    assignees: ["sMiNT0S"]
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: ["dependencies"]
    allow:
      - dependency-type: "direct"
    groups:
      github-actions-core:
        patterns: ["actions/*"]
      github-actions-security:
        patterns: ["github/codeql-action*", "aquasecurity/*"]
