# Dependabot configuration for AIBugBench
# Automated dependency vulnerability scanning and updates

version: 2
updates:
  # Python dependencies in pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    assignees:
      - "sMiNT0S"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"  # Removed 'security' label (label not present in repo)
    allow:  # Focus on both direct & indirect updates
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:  # Group related updates together
      requests-group:
        patterns:
          - "requests*"
          - "urllib3"
          - "certifi"
      yaml-group:
        patterns:
          - "pyyaml"
          - "yaml*"
      dev-tools:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest*"

  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    assignees:
      - "sMiNT0S"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"