site_name: AIBugBench
site_url: https://smintos.github.io/AIBugBench
repo_url: https://github.com/sMiNT0S/AIBugBench
repo_name: sMiNT0S/AIBugBench
docs_dir: docs
strict: true
edit_uri: edit/main/docs/
site_description: Deterministic, local AI code benchmark with sandboxed execution and 7-dimension scoring.
site_author: sMiNT0S

watch:
  - results/ # live-reload when JSON changes

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - header.show-on-scroll
    - header.autohide
    - header.scroll
    - toc.integrate
    - navigation.footer
    - navigation.tracking
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - search.share
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.footnotes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - include-markdown:
      preserve_includer_indent: true
      rewrite_relative_urls: false
  - git-revision-date-localized:
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            docstring_style: numpy
            show_source: false
            show_symbol_type_toc: false
            show_root_heading: true # big H1/H2 per module
            show_root_toc_entry: false
            show_if_no_docstring: false
            show_symbol_type_heading: true # group by Classes / Functions
            separate_signature: true
            signature_crossrefs: true
            heading_level: 2 # modules start at ##
            members_order: source
  - autorefs
  - redirects
  - macros
  - glightbox

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - Reference:
      - API Reference: api-reference.md
      - Scoring Methodology: scoring-methodology.md
      - Architecture: architecture.md
  - Troubleshooting:
      - Troubleshooting Guide: troubleshooting.md
      - Sabotage Notes: sabotage-notes.md
  - Project:
      - Contributing: contributing.md
      - Code of Conduct: code-of-conduct.md
      - Security Policy: security.md
      - License: license.md
      - Roadmap: ROADMAP.md
      - Changelog: https://github.com/sMiNT0S/AIBugBench/blob/main/CHANGELOG.md
  - Internal:
      - Overview: INTERNALS.md
      - Validation Package README: internal/validation-readme.md
      - Scripts README: internal/scripts-readme.md
      - Submissions README: internal/submissions-readme.md
      - Template README: internal/submission-template-readme.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - tables
  - footnotes
  - abbr
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sMiNT0S/AIBugBench
  generator: false
  # Feature flags (used by templates / future macros)
  features:
    internal_docs: true # set to false to hide 'Internal' section (remove nav block manually or via build script)
  announcement: |
    <strong>AIBugBench v0.9.0</strong> — sandboxed execution, deterministic, local. <a href="getting-started/">Start here</a>.

copyright: |
  &copy; 2025 <a href="https://github.com/sMiNT0S/AIBugBench"  target="_blank" rel="noopener">AIBugBench Project</a>
