# Your corrected version of config.yaml
# TODO: Fix all YAML syntax and structure issues

# Requirements:
# 1. Fix all indentation errors
# 2. Ensure consistent formatting
# 3. Preserve all original data
# 4. Convert string booleans to actual booleans
# 5. Convert string numbers to actual numbers
