name: Base Python Setup
description: Checkout, set up Python, install hashed dependencies from locks.
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: ${{ inputs.python-version }}

    # Windows cannot replace a running pip.exe during --require-hashes installs.
    # Locks (compiled with --allow-unsafe) pin pip, pre-upgrade here.
    - name: Windows | pre-satisfy pip pin from lock
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if (Test-Path 'requirements-dev.lock') { $lock = 'requirements-dev.lock' } else { $lock = 'requirements.lock' }
        $m = Select-String -Path $lock -Pattern '^pip==([0-9][^\s;]+)' | Select-Object -First 1
        if ($m) {
          $ver = $m.Matches[0].Groups[1].Value.Trim()
          Write-Host "Upgrading pip to $ver (pre-install)..."
          python -m pip install --upgrade ("pip==" + $ver)
        } else {
          Write-Host "No pip pin found; skipping pre-upgrade."
        }
        python -m pip --version

    - name: Install base (hashed)
      shell: bash
      run: |
        python -m pip install -U pip
        python -m pip install --require-hashes -r requirements.lock

    - name: Install dev/test/security (hashed)
      if: ${{ inputs.install-dev == 'true' || inputs.install-test == 'true' || inputs.install-security == 'true' }}
      shell: bash
      run: |
        python -m pip install --require-hashes -r requirements-dev.lock

inputs:
  python-version:
    description: Python version to use
    required: true
  install-dev:
    description: Install dev/lint/type tools (from dev lock)
    required: false
    default: 'false'
  install-test:
    description: Install test/coverage tools (from dev lock)
    required: false
    default: 'false'
  install-security:
    description: Install security tools (from dev lock)
    required: false
    default: 'false'
