name: Docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read  # build-only; no Pages publish rights

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # explicit job-level; top-level already restricts
    steps:
      - uses: actions/checkout@v5 # Updated to v5 (Node 24 runtime; requires runner >= 2.327.1)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build site (no deploy while repo private)
        run: mkdocs build --strict
      - name: Upload built site as artifact (internal preview)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
      # NOTE: Deploy job intentionally removed for safety while repository remains private.
      # environment block removed to silence editor schema warning.
