name: Docs

on:
  push:
    branches:
      - main
      - refactor/**
  pull_request:
    branches:
      - main
      - refactor/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.13.7'
          check-latest: false
      - name: Install MkDocs and plugins
        run: |
          python -m pip install -U "pip==24.3.1"
          # Docs deps are separate; if a docs lock exists in future, switch to it with --require-hashes
          pip install -r docs/requirements.txt
      # Generate Safety badge JSON to be published under /badges/safety.json on Pages
      - name: Generate Safety badge JSON
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
          SAFETY_DISABLE_ANALYTICS: "1"
          CI: "true"
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "safety>=3,<4"

          # Prefer scanning a lockfile if available; else scan the dev lock
          ARG=""
          if [ -f requirements.lock ]; then
            ARG="--file=requirements.lock"
          elif [ -f requirements-dev.lock ]; then
            ARG="--file=requirements-dev.lock"
          fi

          # Non-interactive Safety v3 scan; tolerate failures to keep docs publishing
          safety scan --key "${SAFETY_API_KEY:-}" $ARG --json > safety-results.json || true

          # Count issues and build Shields.io JSON
          COUNT=$(jq '(.issues // []) | length' safety-results.json 2>/dev/null || echo 0)
          if [ "${COUNT:-0}" -eq 0 ]; then
            COLOR="brightgreen"; MSG="0 vulns"
          else
            COLOR="red"; MSG="${COUNT} vulns"
          fi

          mkdir -p docs/badges
          printf '{"schemaVersion":1,"label":"safety","message":"%s","color":"%s"}\n' "$MSG" "$COLOR" > docs/badges/safety.json
      - name: Build site
        run: mkdocs build --strict
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
