name: Scheduled Dependency Refresh

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # needed for pushing branch
  pull-requests: write

env:
  PYTHON_DEFAULT_VERSION: '3.13'

jobs:
  refresh-locks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{env.PYTHON_DEFAULT_VERSION}}
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install 'pip-tools==7.5.0'
          python -c "import importlib.metadata as m; print('pip-tools', m.version('pip-tools'))"
      - name: Recompile runtime lock (normalized)
        run: |
          python scripts/update_requirements_lock.py
      - name: Recompile dev lock (normalized)
        run: |
          python scripts/update_requirements_lock.py --dev
      - name: Detect changes
        id: diff
        run: |
          git add requirements.lock requirements-dev.lock || true
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Summarize changes to job summary
        if: steps.diff.outputs.changed == 'true'
        run: |
          echo "### Lockfile diff (stat)" >> "$GITHUB_STEP_SUMMARY"
          git --no-pager diff --stat || true
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Changed files:" >> "$GITHUB_STEP_SUMMARY"
          git diff --name-only || true
      - name: Create or update PR
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          commit-message: "deps: refresh lock files"
          title: "chore(deps): refresh lock files"
          body: "Automated lock refresh. See the job summary for a diff stat."
          branch: chore/deps/lock-refresh
          delete-branch: true
          labels: dependencies
          assignees: sMiNT0S
          signoff: true
      - name: Summary
        if: always()
        run: |
          echo '### Scheduled Dependency Refresh' >> $GITHUB_STEP_SUMMARY
          if ["${{steps.diff.outputs.changed}}" = 'true']; then
            echo 'Changes detected; PR created or updated (peter-evans/create-pull-request).' >> $GITHUB_STEP_SUMMARY
          else
            echo 'No changes in locks; nothing to do.' >> $GITHUB_STEP_SUMMARY
