name: Scheduled Dependency Refresh

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # needed for pushing branch
  pull-requests: write

env:
  PYTHON_DEFAULT_VERSION: '3.13'

jobs:
  refresh-locks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install 'pip-tools>=7.5.0'
      - name: Recompile runtime lock
        run: |
          python -m piptools compile --generate-hashes --allow-unsafe -o requirements.lock requirements.txt
      - name: Recompile dev lock
        run: |
          python -m piptools compile --generate-hashes --allow-unsafe -o requirements-dev.lock requirements-dev.txt
      - name: Detect changes
        id: diff
        run: |
          git add requirements.lock requirements-dev.lock || true
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Create PR
        if: steps.diff.outputs.changed == 'true'
        env:
          BRANCH: automated/lock-refresh
        run: |
            set -e
            git config user.name 'github-actions'
            git config user.email 'github-actions@users.noreply.github.com'
            git checkout -B "$BRANCH"
            git commit -m 'chore(deps): scheduled lock refresh' || exit 0
            git push -f origin "$BRANCH"
            gh pr create --title 'chore(deps): scheduled lock refresh' --body 'Automated weekly dependency lock refresh.' --base main || echo "PR already exists"
        shell: bash
      - name: Summary
        if: always()
        run: |
          echo '### Scheduled Dependency Refresh' >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.diff.outputs.changed }}" = 'true' ]; then
            echo 'Changes detected; PR created or updated.' >> $GITHUB_STEP_SUMMARY
          else
            echo 'No changes in locks; nothing to do.' >> $GITHUB_STEP_SUMMARY