name: security-audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run security audit
        run: |
          python scripts/security_audit.py --json > audit.json
          cat audit.json

      - name: Fail if audit not ok
        run: >
          python -c "import json,sys,pathlib;d=json.loads(pathlib.Path('audit.json').read_text());
          ok=bool(d.get('ok'));print('Audit OK:',ok);sys.exit(0 if ok else 1)"