name: Tiered Validation

on:
  push:
    paths:
      - 'submissions/**'
      - 'tests/test_reference_implementations.py'
      - 'tests/test_templates.py'
      - '.github/workflows/tiered-validation.yml'
  pull_request:
    paths:
      - 'submissions/**'
      - 'tests/test_reference_implementations.py'
      - 'tests/test_templates.py'
      - '.github/workflows/tiered-validation.yml'

env:
  PYTHON_VERSION: '3.12'

jobs:
  tier1-reference:
    name: Reference Implementations
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint reference
        run: |
          if [ -d "submissions/reference_implementations" ]; then
            ruff check submissions/reference_implementations/
          fi

      - name: Security scan
        run: |
          if [ -d "submissions/reference_implementations" ]; then
            bandit -c bandit.yaml -r submissions/reference_implementations/
          fi

      - name: Tests (reference)
        run: pytest tests/test_reference_implementations.py -v

  tier2-templates:
    name: Templates (Non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Basic checks
        run: |
          if [ -d "submissions/templates" ]; then
            ruff check submissions/templates/ --config .ruff-tier2.toml || true
            bandit -c bandit-tier2.yaml -r submissions/templates/ || true
          fi

      - name: Tests (templates)
        run: pytest tests/test_templates.py -v || true
